spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true